version: '3.7'

services:
  db:
    image: postgres
    volumes:
      - djm-db:/var/lib/postgresql
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      - DB_USER
      - DB_PASSWORD
      - DB_NAME
    volumes:
      - ./django_admin_manager:/app
      - ./media:/app/media
    ports:
      - 8000:8000
    depends_on:
      - db

volumes:
  djm-db:
